// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyv282ZoHvTVLN-Ydedzhw8ERLDhaZ_n8',
    appId: '1:1017336586923:web:0be9759c7790c7d0934dee',
    messagingSenderId: '1017336586923',
    projectId: 'contactsapp-ed907',
    authDomain: 'contactsapp-ed907.firebaseapp.com',
    storageBucket: 'contactsapp-ed907.firebasestorage.app',
    measurementId: 'G-4YZQK4897R',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb5QjvvVKdSOvF2JyVcu-cn58QYZ6iel4',
    appId: '1:1017336586923:ios:6db0caf6e47872b4934dee',
    messagingSenderId: '1017336586923',
    projectId: 'contactsapp-ed907',
    storageBucket: 'contactsapp-ed907.firebasestorage.app',
    iosClientId: '1017336586923-f6c02180gtn1g8ius76es6psv7navrvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.doanhuukhanh2224802010826Lab04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb5QjvvVKdSOvF2JyVcu-cn58QYZ6iel4',
    appId: '1:1017336586923:ios:6db0caf6e47872b4934dee',
    messagingSenderId: '1017336586923',
    projectId: 'contactsapp-ed907',
    storageBucket: 'contactsapp-ed907.firebasestorage.app',
    iosClientId: '1017336586923-f6c02180gtn1g8ius76es6psv7navrvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.doanhuukhanh2224802010826Lab04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyv282ZoHvTVLN-Ydedzhw8ERLDhaZ_n8',
    appId: '1:1017336586923:web:cb655285dc53b282934dee',
    messagingSenderId: '1017336586923',
    projectId: 'contactsapp-ed907',
    authDomain: 'contactsapp-ed907.firebaseapp.com',
    storageBucket: 'contactsapp-ed907.firebasestorage.app',
    measurementId: 'G-81XLCCP0V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQdgchePDhLJp1-7IepUeVvxdkhYgFmM',
    appId: '1:1017336586923:android:48b4c028bc6bf5e0934dee',
    messagingSenderId: '1017336586923',
    projectId: 'contactsapp-ed907',
    storageBucket: 'contactsapp-ed907.firebasestorage.app',
  );

}